### ISSUE TITLE
Pinegrow 7 Previewing class controls 

### ISSUE THREAD

**Issue by SyDant** [domsinclair/PinegrowBits#1]
When i learn everything pinegrowBits play,testing,try it with my project is nicely good!
but when im using Pinegrow 7 and new feature - Previewing class controls - Quickly select class property value
There a bit problem

- if i using tailwind cdn or start project from scrach that 2 new feature is work perfect
  but when i using external build from PinegrowBits that feature not working, when i select tailwind class and choose any option on hover live preview not work, i need choose option first to see any change
  
  are you know about this @domsinclair ?
  
![image](https://user-images.githubusercontent.com/31112169/205974635-53bd320e-1067-4979-b5e4-c1e56d661222.png)

**Comment by domsinclair** [comment]
Can you tell me which of the repos you are having the issue with and I'll look into it.

**Comment by SyDant** [comment]
using [Basic Tailwind site](https://github.com/domsinclair/PinegrowBits#basic-tailwind-site) and [First Pinegrow project](https://github.com/domsinclair/PinegrowBits#first-pinegrow-project)

![1670352259097](https://user-images.githubusercontent.com/31112169/205995624-eb6b4652-6967-4987-9346-bde699900082.gif)

**Comment by domsinclair** [comment]
Let me look at it and I'll get back to you, it may not be until the morning (as it's getting late here) but I'll figure out what's going on.

**Comment by SyDant** [comment]
thanks you

**Comment by domsinclair** [comment]
Reproduced the issue, just need to establish the actual cause now.

**Comment by SyDant** [comment]
> Reproduced the issue, just need to establish the actual cause now.

take your time, no need hurry

**Comment by domsinclair** [comment]
Currently talking with Pinegrow support about this.  Latest build shows some improvement in this but it's erratic.  Will let you know when I know more myself.

**Comment by domsinclair** [comment]
It would seem that this particular feature only works, currently, with the internal JIT compiler.  They'll be looking to fix this with the next version.  NB that won't be the one that will drop tomorrow but hopefully the one after that.

**Comment by SyDant** [comment]
> 
i see because this is new feature v7 have bug and need testing first alright then, thanks for checking out my issue, sorry i borrow your time hopefully they fix it soon , Thanks you

**Comment by domsinclair** [comment]
Good news, the latest version of Pinegrow V7.03 has fixed this issue and you should now see it working as you expected it to.  Once I have confirmation form you that this is indeed the issue I'll close this issue.

**Comment by SyDant** [comment]
hasben tested using external build and work!
thank you
